/**
 * Layer 5 — Service layer shared DTOs and output types.
 *
 * These types are the contract between services (Layer 5) and API routes
 * (Layer 8). They must not import from app/ or any outer layer.
 *
 * Domain entity types (Device, Report, Alert, etc.) are defined in
 * lib/domain and used directly — no duplication here.
 */

import type { DeviceStatus } from '@/lib/domain';
import type { CreateAlert } from '@/lib/domain';

// ---------------------------------------------------------------------------
// Ingestion pipeline output
// ---------------------------------------------------------------------------

/**
 * The result returned by IngestionService.ingest() when ingestion succeeds.
 * Consumed by the API route to construct its 200 response body.
 */
export interface IngestionOutcome {
  /** UUID of the device this report belongs to. */
  readonly deviceId: string;

  /** UUID of the upserted dd_reports row. */
  readonly reportId: string;

  /** Fully-qualified hostname of the appliance, e.g. "DD6300BSR.iq.zain.com". */
  readonly hostname: string;

  /** ISO date the report covers, e.g. "2026-06-10". */
  readonly reportDate: string;

  /** True when this was the first report ever received from this appliance. */
  readonly isNewDevice: boolean;

  /** True when the exact same raw file (same SHA-256 hash) was already ingested. */
  readonly isReprocessed: boolean;

  /** Number of enabled alert rules evaluated against the report. */
  readonly alertsEvaluated: number;

  /** Number of rule-engine alerts that fired (threshold conditions met). */
  readonly alertsFired: number;

  /** Number of alerts extracted directly from the autosupport file. */
  readonly applianceAlertCount: number;

  /** Overall health status derived by the alert engine. */
  readonly deviceStatus: DeviceStatus;

  /** Non-fatal parse errors encountered; isValid may still be true. */
  readonly parseErrors: readonly string[];

  /** Wall-clock duration of the entire ingest pipeline in milliseconds. */
  readonly durationMs: number;
}

// ---------------------------------------------------------------------------
// Alert engine output
// ---------------------------------------------------------------------------

/**
 * Result of AlertEngineService.evaluate().
 * Contains rule-generated alerts and the derived DeviceStatus.
 */
export interface AlertEvaluationResult {
  /** Overall health status, derived from worst active-alert severity. */
  readonly deviceStatus: DeviceStatus;

  /**
   * Alerts generated by the rule engine.
   * These have source = AlertSource.RuleEngine and no appliance alert_id.
   * Note: reportId is a placeholder here; the ingestion service fills in the
   * real UUID after the report has been upserted.
   */
  readonly engineAlerts: readonly CreateAlert[];

  /** Total number of enabled rules evaluated. */
  readonly rulesEvaluated: number;

  /** Number of rules whose threshold condition was satisfied. */
  readonly rulesFired: number;

  /**
   * True when at least one CRITICAL or WARNING engine alert fired.
   * Used by the ingestion service to decide whether to request a notification.
   */
  readonly notificationRequired: boolean;
}

// ---------------------------------------------------------------------------
// Chart trend data
// ---------------------------------------------------------------------------

/** One data point in a device's storage utilisation trend chart. */
export interface StorageTrendPoint {
  /** ISO date string, e.g. "2026-06-10". */
  readonly date: string;
  readonly totalGib: number;
  readonly usedGib: number;
  readonly usedPercent: number;
  /** Null when the report did not include cleanable space data. */
  readonly cleanableGib: number | null;
}

/** One data point in a device's compression trend chart. */
export interface CompressionTrendPoint {
  readonly date: string;
  /** Overall compression factor (all-time cumulative). Null if not reported. */
  readonly totalFactor: number | null;
  /** Storage reduction percentage. Null if not reported. */
  readonly reductionPercent: number | null;
  /** Last-7-days total compression factor. Null if not reported. */
  readonly last7DaysFactor: number | null;
}

// ---------------------------------------------------------------------------
// Runway estimate
// ---------------------------------------------------------------------------

/**
 * Storage runway projection for one device, based on linear regression of
 * recent daily growth. Answers "when will this device fill up?"
 */
export interface RunwayEstimate {
  readonly deviceId: string;
  readonly hostname: string;

  /** Most recent storage_used_percent (0–100). */
  readonly currentUsedPercent: number;

  /** Average daily growth in GiB derived from the regression slope. */
  readonly avgDailyGrowthGib: number;

  /**
   * Estimated days until usedGib reaches totalGib.
   * Null when avgDailyGrowthGib ≤ 0 (not growing or shrinking).
   */
  readonly estimatedDaysRemaining: number | null;

  /** ISO date of projected fill date. Null when not growing. */
  readonly projectedFillDate: string | null;

  /** Number of daily reports used for the regression. */
  readonly dataPointsUsed: number;

  readonly totalCapacityGib: number | null;
  readonly usedGib: number | null;
}

// ---------------------------------------------------------------------------
// Fleet comparison
// ---------------------------------------------------------------------------

/** One row in the fleet-wide comparison table (one per active device). */
export interface DeviceComparisonRow {
  readonly deviceId: string;
  readonly hostname: string;
  readonly shortName: string;

  /** ISO date of the most recent report. Null if no reports yet. */
  readonly reportDate: string | null;

  readonly totalGib: number | null;
  readonly usedGib: number | null;
  readonly usedPercent: number | null;

  /** All-time cumulative compression factor. Null if not reported. */
  readonly totalFactor: number | null;

  readonly deviceStatus: DeviceStatus;
  readonly failedDisks: number;
  readonly activeAlerts: number;
}

// ---------------------------------------------------------------------------
// Fleet-wide analytics types (used by analytics routes)
// ---------------------------------------------------------------------------

/**
 * One row in the fleet storage trend API response.
 * Each row represents one device on one day. Clients group by date to plot
 * per-device trends or aggregate across devices.
 */
export interface FleetStorageTrendRow {
  readonly deviceId: string;
  readonly hostname: string;
  /** ISO date string, e.g. "2026-06-10". */
  readonly date: string;
  readonly totalGib: number;
  readonly usedGib: number;
  readonly usedPercent: number;
}

/**
 * One row in the fleet daily summary API response.
 * Aggregates device counts and storage across the whole fleet for a given day.
 * Days with no reports from any device are omitted.
 */
export interface FleetDailySummaryRow {
  /** ISO date string, e.g. "2026-06-10". */
  readonly date: string;
  readonly totalDevices: number;
  readonly healthyCount: number;
  readonly warningCount: number;
  readonly criticalCount: number;
  readonly unknownCount: number;
  /** Sum of totalGib across all reporting devices. */
  readonly totalCapacityGib: number;
  /** Sum of usedGib across all reporting devices. */
  readonly totalUsedGib: number;
  /** Sum of activeTotalAlerts across all reporting devices. */
  readonly totalActiveAlerts: number;
}

/**
 * One row in the alert trend API response.
 * Shows alert counts per severity for a single day.
 * Days with zero alerts are included so charts don't have gaps.
 */
export interface AlertTrendRow {
  /** ISO date string, e.g. "2026-06-10". */
  readonly date: string;
  readonly criticalCount: number;
  readonly warningCount: number;
  readonly infoCount: number;
}

/**
 * Fleet-wide health summary used by the System Health page stat cards.
 */
export interface FleetHealthSummary {
  readonly totalDevices: number;
  readonly healthyCount: number;
  readonly warningCount: number;
  readonly criticalCount: number;
  readonly unknownCount: number;
  /** Sum of totalGib across all active devices (from last snapshot). */
  readonly totalCapacityGib: number;
  /** Sum of usedGib across all active devices (from last snapshot). */
  readonly totalUsedGib: number;
  /** Fleet-wide average storage utilisation percent (0–100). */
  readonly avgUsedPercent: number;
  /** Total active alerts across the fleet right now. */
  readonly totalActiveAlerts: number;
}

/**
 * Per-device ingestion pipeline status.
 * Used by the System Health page ingestion status table.
 */
export interface IngestionStatusPerDevice {
  readonly deviceId: string;
  readonly hostname: string;
  readonly shortName: string;
  /** ISO date of the last ingested report. Null if never ingested. */
  readonly lastReportDate: string | null;
  /** Hours since the last report was received. Null if never ingested. */
  readonly lastReportAgeHours: number | null;
  /**
   * True when no report has been received for today and the current UTC hour
   * is past config.REPORT_DEADLINE_HOUR.
   */
  readonly isOverdue: boolean;
  readonly lastStatus: DeviceStatus;
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/** Output of ExportService.generateReport(). */
export interface ExportReport {
  /**
   * Complete, self-contained HTML document ready for browser printing.
   * Includes all CSS inline; no external dependencies.
   */
  readonly htmlContent: string;

  /** Suggested download file name, e.g. "DD6300BSR-2026-06-10-report.html". */
  readonly fileName: string;

  /** ISO date of the exported report, e.g. "2026-06-10". */
  readonly reportDate: string;

  /** Fully-qualified hostname of the appliance. */
  readonly hostname: string;
}
