/**
 * Alert entity — a single alert record associated with a device report.
 *
 * Alerts come from two sources:
 *   1. Extracted directly from the autosupport file's "Current Alerts" and
 *      "Alerts History" sections (source = AlertSource.Appliance).
 *   2. Generated by the DD Monitor internal alert rule engine after evaluating
 *      thresholds (source = AlertSource.RuleEngine).
 *
 * One Alert corresponds to one row in dd_alerts.
 */

import { AlertSeverity } from '../enums/alert-severity.enum';

// ---------------------------------------------------------------------------
// Enums defined alongside the entity they belong to
// ---------------------------------------------------------------------------

/**
 * Where an alert originated.
 * Stored in dd_alerts.source — affects de-duplication and display labelling.
 */
export enum AlertSource {
  /** Extracted from the autosupport file's alert tables. */
  Appliance  = 'appliance',
  /** Generated by the DD Monitor internal alert rule engine. */
  RuleEngine = 'rule_engine',
}

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A single alert record associated with a device and a specific ingested report. */
export interface Alert {
  /** Supabase-generated UUID, primary key in dd_alerts. */
  readonly id: string;

  /** Foreign key to dd_devices.id. */
  readonly deviceId: string;

  /** Foreign key to dd_reports.id — the report that produced this alert. */
  readonly reportId: string;

  /** Denormalized report date for efficient date-range queries without a join. */
  readonly reportDate: Date;

  /**
   * The Data Domain appliance's internal alert identifier, e.g. "p0-273".
   * Null for rule-engine-generated alerts (they have no DD-native id).
   */
  readonly alertId: string | null;

  /** Severity level, matching the string in the autosupport file. */
  readonly severity: AlertSeverity;

  /**
   * Alert class as reported by the appliance, e.g. "Network", "Storage", "Hardware".
   * Null for rule-engine alerts (class is inferred from the rule).
   */
  readonly class: string | null;

  /**
   * The specific object affected, e.g. "Interface Index=20", "Disk Slot 3".
   * Null when the appliance does not specify one.
   */
  readonly object: string | null;

  /**
   * Full alert message text from the appliance or rule engine description.
   * Example: "EVT-NETM-00001 A network interface has gone down."
   */
  readonly message: string;

  /**
   * Timestamp when the alert first fired on the appliance.
   * Null for rule-engine alerts (creation time is ingestedAt on the report).
   */
  readonly postTime: Date | null;

  /**
   * Timestamp when the alert was cleared on the appliance.
   * Null when the alert is still active.
   */
  readonly clearTime: Date | null;

  /**
   * Whether the alert is currently active (not yet cleared).
   * Derived from clearTime === null at parse time.
   */
  readonly isActive: boolean;

  /** Whether this alert came from the appliance itself or from the rule engine. */
  readonly source: AlertSource;

  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new Alert record.
 * id and createdAt are generated by the database.
 */
export type CreateAlert = Omit<Alert, 'id' | 'createdAt'>;
