/**
 * Device entity — a Data Domain appliance registered in the DD Monitor fleet.
 *
 * One Device corresponds to one row in dd_devices. It is populated on first
 * successful ingestion and updated on every subsequent report. The denormalized
 * snapshot fields (lastStatus, lastUsedPercent, etc.) are refreshed by a
 * database trigger after each ingest, so dashboard list queries never need to
 * join against dd_reports for the current state.
 */

import { type Gib } from '../value-objects/gib.vo';
import { type StoragePercent } from '../value-objects/storage-percent.vo';
import { DeviceStatus } from '../enums/device-status.enum';

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A Data Domain appliance registered in the DD Monitor fleet. */
export interface Device {
  /** Supabase-generated UUID, primary key in dd_devices. */
  readonly id: string;

  /** Fully-qualified hostname as reported by the appliance, e.g. DD6300BSR.iq.zain.com. */
  readonly hostname: string;

  /**
   * Short site-code derived from the hostname, e.g. "BSR" from "DD6300BSR.iq.zain.com".
   * Used in compact tiles and charts where the full hostname is too long.
   */
  readonly shortName: string;

  /** Hardware model string, e.g. "DD6300". Null until the first successful ingest. */
  readonly model: string | null;

  /** Dell product serial number, e.g. "CKM00193901494". */
  readonly serialNumber: string | null;

  /** Chassis serial number, e.g. "FCNCS190702089". */
  readonly chassisSerial: string | null;

  /** Physical or logical location of the appliance, e.g. "Basra". */
  readonly location: string | null;

  /** Data Domain OS version string, e.g. "Data Domain OS 6.2.0.30-629757". */
  readonly osVersion: string | null;

  /**
   * Hardware-level raw storage capacity. Changes only on hardware expansion.
   * Null until the first successful ingest.
   */
  readonly totalCapacity: Gib | null;

  /**
   * Whether the device is actively monitored.
   * false = soft-deleted or decommissioned; still visible in history but not
   * included in fleet-wide health counts.
   */
  readonly isActive: boolean;

  // --- Denormalized snapshot (refreshed by DB trigger on each ingest) ---

  /** Date of the most recently ingested report for this device. */
  readonly lastReportDate: Date | null;

  /** Timestamp of the last successful ingest for this device. */
  readonly lastSeenAt: Date | null;

  /** Storage utilisation percent from the most recent report. */
  readonly lastUsedPercent: StoragePercent | null;

  /** Overall health status derived from the most recent alert-rule evaluation. */
  readonly lastStatus: DeviceStatus;

  /** Count of active alerts (non-cleared) in the most recent report. */
  readonly lastActiveAlerts: number;

  readonly createdAt: Date;
  readonly updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Construction / mutation types
// ---------------------------------------------------------------------------

/**
 * Data required to create a new Device record.
 * id, snapshot fields, and timestamps are generated by the system.
 */
export interface CreateDevice {
  readonly hostname: string;
  readonly shortName: string;
  readonly model?: string;
  readonly serialNumber?: string;
  readonly chassisSerial?: string;
  readonly location?: string;
  readonly osVersion?: string;
  readonly totalCapacity?: Gib;
}

/**
 * Partial update applied to an existing Device.
 * Only the fields listed here can change after creation.
 */
export interface UpdateDevice {
  readonly model?: string;
  readonly serialNumber?: string;
  readonly chassisSerial?: string;
  readonly location?: string;
  readonly osVersion?: string;
  readonly totalCapacity?: Gib;
  readonly isActive?: boolean;
  /** Updated by DeviceRepository after ingest (snapshot refresh). */
  readonly lastReportDate?: Date;
  /** Updated by DeviceRepository after ingest (snapshot refresh). */
  readonly lastSeenAt?: Date;
  /** Updated by DeviceRepository after ingest (snapshot refresh). */
  readonly lastUsedPercent?: StoragePercent;
  /** Updated by AlertEngine via DeviceRepository after rule evaluation. */
  readonly lastStatus?: DeviceStatus;
  /** Updated by AlertEngine via DeviceRepository after rule evaluation. */
  readonly lastActiveAlerts?: number;
}

// ---------------------------------------------------------------------------
// Domain helper
// ---------------------------------------------------------------------------

/**
 * Extracts a short, human-readable site code from a DD appliance hostname.
 *
 * Pattern: The DD series model number (DD followed by digits) is immediately
 * followed by an uppercase site code.
 *
 * Examples:
 *   "DD6300BSR.iq.zain.com"  → "BSR"
 *   "DD6300BGH.iq.zain.com"  → "BGH"
 *   "DD990KBSR.iq.zain.com"  → "BSR"
 *
 * Falls back to the first FQDN segment if the pattern is not matched.
 *
 * @param hostname - The FQDN hostname of the appliance.
 * @returns A short site-code string.
 */
export function deriveShortName(hostname: string): string {
  // Match DD followed by digits, then one or more uppercase letters (site code).
  const match = /DD\d+([A-Z]+)/i.exec(hostname);
  if (match !== null) {
    const siteCode = match[1];
    if (siteCode !== undefined && siteCode.length > 0) {
      return siteCode.toUpperCase();
    }
  }
  // Fallback: first label of the FQDN (e.g. "DD6300BSR" from "DD6300BSR.iq.zain.com")
  const firstLabel = hostname.split('.')[0];
  return firstLabel ?? hostname;
}
