/**
 * Disk entity — a physical disk slot within a Data Domain enclosure.
 *
 * Extracted from the HARDWARE CONFIGURATION section of the autosupport file.
 * One Disk corresponds to one row in dd_disks (replaced in full on each ingest).
 *
 * DD6300BSR physical layout (from the real sample file):
 *   Enclosure 1: DD6300 — 14 slots (active tier, slots 0–13)
 *   Enclosure 2: ES30   — 15 slots (expansion, slots 0–14)
 * Typical state: 25 disks in use + 2 spares = 27 total across both enclosures.
 */

import { type Gib } from '../value-objects/gib.vo';

// ---------------------------------------------------------------------------
// Enums defined alongside the entity they belong to
// ---------------------------------------------------------------------------

/**
 * Which storage tier a disk belongs to on the appliance.
 */
export enum DiskTier {
  /** Primary active-tier disk (used for online deduplication storage). */
  Active  = 'active',
  /** Cache-tier disk (SSD/NVMe, used for read acceleration). */
  Cache   = 'cache',
  /** Tier could not be determined from the autosupport data. */
  Unknown = 'unknown',
}

/**
 * Operational state of a physical disk slot.
 * Values match the dd status column in the HARDWARE CONFIGURATION section.
 */
export enum DiskState {
  /** Disk is installed and actively used for storage or cache. */
  InUse   = 'in_use',
  /** Disk is installed and designated as a hot spare. */
  Spare   = 'spare',
  /** Disk has failed or been removed from service. Triggers a CRITICAL alert. */
  Failed  = 'failed',
  /** Slot is empty (no disk installed). */
  Absent  = 'absent',
  /** State could not be determined from the autosupport data. */
  Unknown = 'unknown',
}

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A physical disk slot within a Data Domain appliance enclosure. */
export interface Disk {
  /** Supabase-generated UUID, primary key in dd_disks. */
  readonly id: string;

  /** Foreign key to dd_devices.id. */
  readonly deviceId: string;

  /** Foreign key to dd_reports.id — the report this disk snapshot belongs to. */
  readonly reportId: string;

  /** Denormalized report date for date-range queries without a join. */
  readonly reportDate: Date;

  /**
   * Enclosure number (1-indexed), e.g. 1 for the base shelf, 2 for an ES30.
   * Null if the parser could not determine the enclosure.
   */
  readonly enclosureId: number | null;

  /** Enclosure hardware model, e.g. "DD6300" or "ES30". Null if not available. */
  readonly enclosureModel: string | null;

  /** Enclosure chassis serial number. Null if not available. */
  readonly enclosureSerial: string | null;

  /**
   * Slot number within the enclosure (0-indexed).
   * Null if the parser could not determine the slot.
   */
  readonly slotNumber: number | null;

  /**
   * Human-readable disk label, e.g. "Enclosure1-Slot3".
   * Null if a label could not be derived.
   */
  readonly label: string | null;

  /** Which storage tier this disk serves. */
  readonly tier: DiskTier;

  /** Operational state of the disk slot. */
  readonly state: DiskState;

  /** Disk model string as reported by the appliance, e.g. "SEAGATE ST4000NM0023". */
  readonly model: string | null;

  /** Disk serial number from the appliance inventory. */
  readonly serialNumber: string | null;

  /** Firmware version string as reported by the appliance. */
  readonly firmwareVersion: string | null;

  /** Raw disk capacity in GiB. Null if not reported in the autosupport file. */
  readonly capacityGib: Gib | null;

  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new Disk record.
 * id and createdAt are generated by the database.
 */
export type CreateDisk = Omit<Disk, 'id' | 'createdAt'>;
