/**
 * EmailNotification entity — a record of an outbound alert email.
 *
 * Written by NotificationService after every send attempt (success or failure).
 * Used by the has_email_been_sent_today() de-duplication check to prevent
 * duplicate alerts on re-ingest, and by the System Health page email history panel.
 *
 * One EmailNotification corresponds to one row in email_notifications.
 */

import { EmailType } from '../enums/email-type.enum';

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/** Delivery outcome of an email send attempt. */
export type EmailStatus = 'sent' | 'failed';

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A record of one outbound email dispatch attempt. */
export interface EmailNotification {
  /** Supabase-generated UUID, primary key in email_notifications. */
  readonly id: string;

  /** Category of this notification, used for de-duplication. */
  readonly emailType: EmailType;

  /**
   * The device this notification concerns.
   * Null for system-wide notifications (e.g. WeeklyReport).
   */
  readonly deviceId: string | null;

  /**
   * The calendar date this notification is for.
   * Part of the de-duplication key: (emailType, deviceId, reportDate).
   * Null for notifications not tied to a specific report date.
   */
  readonly reportDate: Date | null;

  /** Recipient email addresses. */
  readonly recipients: readonly string[];

  /** Subject line of the email as sent. */
  readonly subject: string;

  /**
   * First ~500 characters of the email body.
   * Shown in the System Health email history panel.
   */
  readonly bodyPreview: string | null;

  /** Whether the email was delivered or failed. */
  readonly status: EmailStatus;

  /** Error detail if status = failed. Null on success. */
  readonly errorMessage: string | null;

  /** Timestamp of the send attempt. */
  readonly sentAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new EmailNotification.
 * id and sentAt are generated by the database.
 */
export type CreateEmailNotification = Omit<EmailNotification, 'id' | 'sentAt'> & {
  readonly sentAt?: Date;
};
