/**
 * MTree entity — a Data Domain virtual filesystem (MTree / data collection).
 *
 * MTrees are the primary data-organisation unit on DD appliances. Each backup
 * client or application typically writes to its own MTree. They are extracted
 * from the "DM ASTATS" section of the autosupport file.
 *
 * Real examples from DD6300BSR.iq.zain.com autosupport:
 *   1: backup,1574169456,#Inode=4,...,RW
 *   2: ntrkbsr_new,1589978419,#Inode=1567658,...,RW
 *
 * One MTree corresponds to one row in dd_mtrees (replaced in full on each ingest).
 */

import { type Gib } from '../value-objects/gib.vo';

// ---------------------------------------------------------------------------
// Enums defined alongside the entity they belong to
// ---------------------------------------------------------------------------

/**
 * Access mode of an MTree.
 * Values match the trailing flag in the DM ASTATS block (RW or RO).
 */
export enum MTreeStatus {
  /** Read-write: normal operational state. */
  ReadWrite = 'RW',
  /** Read-only: typically set during replication or maintenance. */
  ReadOnly  = 'RO',
  /** Access mode could not be determined from the autosupport data. */
  Unknown   = 'unknown',
}

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/**
 * A Data Domain MTree (virtual filesystem / data collection).
 * Stores pre- and post-compression sizes extracted from DM ASTATS.
 */
export interface MTree {
  /** Supabase-generated UUID, primary key in dd_mtrees. */
  readonly id: string;

  /** Foreign key to dd_devices.id. */
  readonly deviceId: string;

  /** Foreign key to dd_reports.id — the report this MTree snapshot belongs to. */
  readonly reportId: string;

  /** Denormalized report date for date-range queries without a join. */
  readonly reportDate: Date;

  /**
   * MTree name as reported by the appliance, e.g. "backup", "ntrkbsr_new".
   * Used as the display label in the MTree table on the Device Detail page.
   */
  readonly name: string;

  /**
   * Data Domain internal MTree identifier (numeric string), e.g. "1574169456".
   * Stable across reports for the same logical MTree.
   */
  readonly mtreeId: string;

  /** Whether the MTree is in read-write or read-only mode. */
  readonly status: MTreeStatus;

  /**
   * Pre-compression (logical) size in GiB.
   * Null if the DM ASTATS section did not include size data.
   */
  readonly preCompGib: Gib | null;

  /**
   * Post-compression (physical) size in GiB.
   * Null if the DM ASTATS section did not include size data.
   */
  readonly postCompGib: Gib | null;

  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new MTree record.
 * id and createdAt are generated by the database.
 */
export type CreateMTree = Omit<MTree, 'id' | 'createdAt'>;
