/**
 * NetworkPort entity — a network interface on a Data Domain appliance.
 *
 * Extracted from the "Net Show Hardware" section of the autosupport file.
 * One NetworkPort corresponds to one row in dd_network_ports (replaced in full
 * on each ingest).
 *
 * DD6300BSR interface inventory (from the real sample file):
 *   ethMa  — management port
 *   eth1a, eth1b, eth1c, eth1d — first NIC
 *   eth3a, eth3b, eth3c, eth3d — second NIC
 *
 * Known condition in the sample: eth1d shows State "up" but Link "no",
 * which is the source of the CRITICAL alert EVT-NETM-00001 (interface down).
 * The parser captures both State and Link; this entity stores the derived
 * `isDown` flag for quick dashboard queries.
 */

// ---------------------------------------------------------------------------
// Enums defined alongside the entity they belong to
// ---------------------------------------------------------------------------

/**
 * Link state of a network port as reported in the "Net Show Hardware" section.
 * Values are normalized strings derived from the raw autosupport table columns.
 */
export enum PortLinkState {
  /** Port is connected and actively passing traffic. */
  Running = 'running',
  /**
   * Port is administratively up but the link partner is not detected.
   * This is the state associated with EVT-NETM-00001 alerts.
   */
  Up      = 'up',
  /** Link is down; cable unplugged or partner is off. */
  Down    = 'down',
  /** Link state could not be determined from the autosupport data. */
  Unknown = 'unknown',
}

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A network interface port on a Data Domain appliance. */
export interface NetworkPort {
  /** Supabase-generated UUID, primary key in dd_network_ports. */
  readonly id: string;

  /** Foreign key to dd_devices.id. */
  readonly deviceId: string;

  /** Foreign key to dd_reports.id — the report this port snapshot belongs to. */
  readonly reportId: string;

  /** Denormalized report date for date-range queries without a join. */
  readonly reportDate: Date;

  /**
   * Port name as reported by the appliance, e.g. "eth1a", "eth1d", "ethMa".
   * Used as the display label in the network table on the Device Detail page.
   */
  readonly name: string;

  /**
   * Negotiated link speed, e.g. "1000Mb/s", "10000Mb/s".
   * Null if the appliance reported "unknown" or the column was absent.
   */
  readonly speed: string | null;

  /**
   * Duplex mode, e.g. "full", "half".
   * Null if the appliance reported "unknown" or the column was absent.
   */
  readonly duplex: string | null;

  /** Physical media type, e.g. "Copper", "Fiber". Null if not reported. */
  readonly physicalType: string | null;

  /** MAC address, e.g. "00:60:16:a8:df:34". Null if not reported. */
  readonly hardwareAddress: string | null;

  /** Normalised link state derived from the State and Link columns. */
  readonly linkState: PortLinkState;

  /**
   * True when the port is NOT in the Running state.
   * This is the flag checked by the alert rule engine and the dashboard badge.
   */
  readonly isDown: boolean;

  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new NetworkPort record.
 * id and createdAt are generated by the database.
 */
export type CreateNetworkPort = Omit<NetworkPort, 'id' | 'createdAt'>;
