/**
 * SystemLog entity — a structured event record in the system_logs table.
 *
 * Written by every major operation in the system:
 *   - IngestionService (start, success, failure)
 *   - AlertEngine (evaluation outcome, alerts fired)
 *   - NotificationService (email dispatched)
 *   - CleanupService (retention purge runs)
 *   - API auth middleware (key validation)
 *
 * Drives the Logs page of the dashboard, which provides real-time visibility
 * into every pipeline event for system administrators.
 */

import { EventType } from '../enums/event-type.enum';

// ---------------------------------------------------------------------------
// Enums defined alongside the entity they belong to
// ---------------------------------------------------------------------------

/**
 * Severity of a system log entry.
 * Distinct from AlertSeverity — this describes the health of DD Monitor itself,
 * not the health of the appliances it monitors.
 */
export enum LogSeverity {
  /** Normal operational event (ingest completed, email sent, cleanup ran). */
  Info    = 'INFO',
  /** Degraded condition that was handled without aborting the operation. */
  Warning = 'WARNING',
  /** Operation failed; may require manual intervention. */
  Error   = 'ERROR',
}

// ---------------------------------------------------------------------------
// Main entity
// ---------------------------------------------------------------------------

/** A structured event record in the DD Monitor system log. */
export interface SystemLog {
  /** Supabase-generated UUID, primary key in system_logs. */
  readonly id: string;

  /** The category of event this entry records. Used for log-page filtering. */
  readonly eventType: EventType;

  /** Whether the event represents normal operation, a warning, or a failure. */
  readonly severity: LogSeverity;

  /**
   * The device this event concerns, if any.
   * Null for system-wide events (cleanup runs, auth events, etc.).
   */
  readonly deviceId: string | null;

  /**
   * Human-readable summary of the event, e.g.
   * "Ingest completed for DD6300BSR.iq.zain.com — 3 new alerts".
   */
  readonly message: string;

  /**
   * Structured diagnostic context for the event.
   * Contains typed fields relevant to the event type (fileName, parseErrors,
   * alertCount, duration, etc.). Rendered as a collapsible detail panel in
   * the Logs page. Never contains secrets or raw file content.
   */
  readonly details: Record<string, unknown> | null;

  /**
   * Correlation ID linking all log entries from a single ingest operation.
   * Set by IngestionService using crypto.randomUUID(). Null for events that
   * are not part of a multi-step pipeline.
   */
  readonly correlationId: string | null;

  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Construction type
// ---------------------------------------------------------------------------

/**
 * Data required to insert a new SystemLog entry.
 * id and createdAt are generated by the database.
 */
export type CreateSystemLog = Omit<SystemLog, 'id' | 'createdAt'>;
